name: "Unit Test for Android"
description: "Runs Unit Test for android the app using ./gradlew."

runs:
  using: "composite"
  steps:
    - name: Unit Tests
      run: |
        ./gradlew testDebugUnitTest jacocoTestReport
      shell: bash