name: "UI Test for Android"
description: "Runs UI Tests (instrumentation tests)"

runs:
  using: "composite"
  steps:
    - name: UI Tests
      run: |
        ./gradlew connectedDebugAndroidTest
      shell: bash