name: 'Create XCFramework'
description: 'Creates an xcframework and saves it as a .zip'
inputs:
  scheme:
    description: 'Provide the scheme that will be built for distribution'
    required: false
    default: ''
  framework_name:
    description: 'Spoecify the input & output framework name'
    required: false
    default: ''
  path:
    description: "The path to the Swift Package or Xcode project (relative to the repository root)"
    required: true

runs:
  using: "composite"
  steps:
    - name: Build iOS
      shell: bash
      run: |
        pushd "${{ inputs.path }}"
        xcodebuild build -scheme ${{ inputs.scheme }} -destination "generic/platform=iOS" -configuration Release -derivedDataPath ./build BUILD_LIBRARY_FOR_DISTRIBUTION=YES SWIFT_DISABLE_AUTOMATIC_PREVIEWS=YES SKIP_INSTALL=NO
        popd
    - name: Build iOS Simulator
      shell: bash
      run: |
        pushd "${{ inputs.path }}"
        xcodebuild build -scheme ${{ inputs.scheme }} -destination "generic/platform=iOS Simulator" -configuration Release -derivedDataPath ./build BUILD_LIBRARY_FOR_DISTRIBUTION=YES SWIFT_DISABLE_AUTOMATIC_PREVIEWS=YES SKIP_INSTALL=NO
        popd
    - name: Create xcframework
      shell: bash
      run: |
        chmod +x maven.sh ./.github/actions/xcframework-spm-ios/xcf.sh
        ./.github/actions/xcframework-spm-ios/xcf.sh ${{ inputs.scheme }}
    - name: Zip xcframework
      shell: bash
      run: |
        zip -r ./${{ inputs.framework_name }}.xcframework.zip ./${{ inputs.framework_name }}.xcframework