name: 'Create XCFramework'
description: 'Creates an xcframework and saves it as a .zip'
inputs:
  scheme:
    description: 'Provide the scheme that will be built for distribution'
    required: false
    default: ''
  framework_name:
    description: 'Spoecify the input & output framework name'
    required: false
    default: ''
  path:
    description: "The path to the Swift Package or Xcode project (relative to the repository root)"
    required: true

runs:
  using: "composite"
  steps:
    - name: Make xcf.sh executable
      run: chmod +x ${{ github.action_path }}/xcf.sh
      shell: bash

    - name: Create xcframework
      run: ${{ github.action_path }}/xcf.sh
      shell: bash
      
    - name: Zip xcframework
      shell: bash
      run: |
        zip -r ./${{ inputs.framework_name }}.xcframework.zip ./${{ inputs.framework_name }}.xcframework