name: "Publish to TestFlight"
description: "Push a new beta build to TestFlight"

inputs:
  release_notes:
    description: "Publish release notes"
    required: true
  contact_email:
    description: "Contact email for TestFlight"
    required: true
  contact_first_name:
    description: "Contact first name for TestFlight"
    required: true
  contact_last_name:
    description: "Contact last name for TestFlight"
    required: true
  contact_phone:
    description: "Contact phone for TestFlight"
    required: true
  demo_account_name:
    description: "Demo account name for TestFlight"
    required: true
  demo_account_password:
    description: "Demo account password for TestFlight"
    required: true
  fastlane_password:
    description: "Password for Fastlane session"
    required: true

runs:
  using: "composite"
  steps:
    - name: Install dependencies with Bundler
      run: |
        bundle install
      shell: bash

    - name: Debug Inputs
      run: |
        echo "Release Notes: '${{ inputs.release_notes }}'"
        echo "Contact Email: '${{ inputs.contact_email }}'"
        echo "Contact First Name: '${{ inputs.contact_first_name }}'"
        echo "Contact Last Name: '${{ inputs.contact_last_name }}'"
        echo "Contact Phone: '${{ inputs.contact_phone }}'"
        echo "Demo Account Name: '${{ inputs.demo_account_name }}'"
        echo "Demo Account Password: '${{ inputs.demo_account_password }}'"
      shell: bash

    - name: Run Fastlane publish_app lane
      run: |
        fastlane ios publish_app \
          release_notes:"${{ inputs.release_notes }}" \
          contact_email:"${{ inputs.contact_email }}" \
          contact_first_name:"${{ inputs.contact_first_name }}" \
          contact_last_name:"${{ inputs.contact_last_name }}" \
          contact_phone:"${{ inputs.contact_phone }}" \
          demo_account_name:"${{ inputs.demo_account_name }}" \
          demo_account_password:"${{ inputs.demo_account_password }}"
      shell: bash
      env:
        FASTLANE_PASSWORD: ${{ inputs.fastlane_password }}