name: "Sign"
description: "Runs prepare signing that actually uses Match file for installing the correct provisioning profile."

inputs:
  release_notes:
    description: "Publish release notes"
    required: true
  contact_email:
    description: "Contact email for testflight"
    required: true
  contact_first_name:
    description: "Contact first name for testflight"
    required: true
  contact_last_name:
    description: "Contact first name for testflight"
    required: true
  contact_phone:
    description: "Contact phone for testflight"
    required: true
  demo_account_name:
    description: "Contact phone for testflight"
    required: true
  demo_account_password:
    description: "Contact phone for testflight"
    required: true
  fastlane_password:
    description: "ENV for fastlane pwd"
    required: true

runs:
  using: "composite"
  steps:
    - name: Install dependencies with Bundler
      run: |
        bundle install
      shell: bash

    - name: Run Fastlane publish_app lane
      run: |
        fastlane ios publish_app \ 
          release_notes:${{ inputs.release_notes }} \
          contact_email:${{ inputs.contact_email }} \ 
          contact_first_name:${{ inputs.contact_first_name }} \ 
          contact_last_name:${{ inputs.contact_last_name }} \ 
          contact_phone:${{ inputs.contact_phone }} \ 
          demo_account_name:${{ inputs.demo_account_name }} \ 
          demo_account_password:${{ inputs.demo_account_password }}
      shell: bash
      env:
        FASTLANE_PASSWORD: ${{ inputs.fastlane_password }}