name: "Sign"
description: "Runs prepare signing that actually uses Match file for installing the correct provisioning profile."

inputs:
  release_notes:
    description: "Publish release notes"
    required: true
  contact_email:
    description: "Contact email for testflight"
    required: true
  contact_first_name:
    description: "Contact first name for testflight"
    required: true
  contact_last_name:
    description: "Contact first name for testflight"
    required: true
  contact_phone:
    description: "Contact phone for testflight"
    required: true
  demo_account_name:
    description: "Contact phone for testflight"
    required: true
  demo_account_password:
    description: "Contact phone for testflight"
    required: true

runs:
  using: "composite"
  steps:
    - name: Install dependencies with Bundler
      run: |
        bundle install
      shell: bash

    - name: Run Fastlane prepare_signing lane
      run: |
        fastlane ios publish_app release_notes:${{ input.release_notes }} contact_email:${{ input.contact_email }} contact_first_name:${{ input.contact_first_name }} contact_last_name:${{ input.contact_last_name }} contact_phone:${{ input.contact_phone }} demo_account_name:${{ input.demo_account_name }} demo_account_password:${{ input.demo_account_password }}
      shell: bash
      env:
        FASTLANE_PASSWORD: $FASTLANE_PASSWORD