name: "Build Release"
description: "Runs build release for an iOS application"
inputs:
  workspace:
    description: "Xcode Workspace"
    required: false
  scheme:
    description: "Xcode Scheme"
    required: true
  keychain_password:
    description: "Build Machine keychain pwd"
    required: true
  keychain_path:
    description: "Build Machine keychain path"
    required: true
  provisioning_profiles:
    description: "A sting of the following format: { com.example.app => AppProfile, com.example.app.NotificationService => NotificationProfile }"
    required: true

runs:
  using: "composite"
  steps:
    - name: Prepare bundle
      run: |
        bundle install
      shell: bash
    - name: Run fastlane build_release
      run: |
        bundle exec fastlane ios build_release_multiple_targets workspace:${{ inputs.workspace }}  scheme:${{ inputs.scheme }} keychain_password:${{ inputs.keychain_password }} keychain_path:${{ inputs.keychain_path }} provisioning_profiles:"${{ inputs.provisioning_profiles }}"
      shell: bash