name: "Build Release"
description: "Runs build release for an iOS application"
inputs:
  workspace:
    description: "Xcode Workspace"
    required: false
  scheme:
    description: "Xcode Scheme"
    required: true
  keychain_password:
    description: "Build Machine keychain pwd"
    required: true
  keychain_path:
    description: "Build Machine keychain path"
    required: true
  app_id:
    description: "iOS AppID"
    required: true
  provisioning_profile:
    description: "iOS App Provisioning provile - starts with match...."
    required: true
  extension_app_id:
    description: "iOS Extensio AppID"
    required: true
  extension_provisioning_profile:
    description: "iOS Extension App Provisioning provile - starts with match...."
    required: true

runs:
  using: "composite"
  steps:
    - name: Prepare bundle
      run: |
        bundle install
      shell: bash
    - name: Run fastlane build_release_multiple_targets
      run: |
        bundle exec fastlane ios build_release_multiple_targets workspace:${{ inputs.workspace }}  scheme:${{ inputs.scheme }} keychain_password:${{ inputs.keychain_password }} keychain_path:${{ inputs.keychain_path }} app_id:${{ inputs.app_id }} provisioning_profile:"${{ inputs.provisioning_profile }}" extension_app_id:${{ inputs.extension_app_id }} extension_provisioning_profile:"${{ inputs.extension_provisioning_profile }}"
      shell: bash