name: "Build Release"
description: "Runs build release for an iOS application"
inputs:
  scheme:
    description: "Xcode Scheme"
    required: true
  keychain_password:
    description: "Build Machine keychain pwd"
    required: true
  keychain_path:
    description: "Build Machine keychain path"
    required: true
  app_id:
    description: "iOS AppID"
    required: true
  providioning_profile:
    description: "iOS App Provisioning provile - starts with match...."
    required: true

runs:
  using: "composite"
  steps:
    - name: Prepare bundle
      run: |
        bundle install
      shell: bash
    - name: Run fastlane build_release
      run: |
        fastlane ios build_release scheme:${{ inputs.scheme }} keychain_password:${{ inputs.keychain_password }} keychain_path:${{ inputs.keychain_path }} app_id:${{ inputs.app_id }} providioning_profile:${{ inputs.providioning_profile }} 
      shell: bash