name: "Run Xcodebuild Tests with Coverage"
description: "Run tests with xcodebuild, enable code coverage, and validate against a threshold"
inputs:
  scheme:
    description: "The Xcode scheme used to build and test"
    required: true
  project:
    description: "The Xcode project to build and test"
    required: true
  device:
    description: "The device to use for the test destination (e.g., 'iPhone 16')"
    required: true
  os:
    description: "The OS version to use for the test destination (e.g., '16.0')"
    required: true
  testPlan:
    description: "The test plan to use"
    required: true
  enableCodeCoverage:
    description: "YES/NO"
    required: true
    default: 'YES'

runs:
  using: "composite"
  steps:
    - name: Run Tests
      run: |
        # Run tests with coverage enabled
        xcodebuild -scheme "${{ inputs.scheme }}" \
                   -project "${{ inputs.project }}" \
                   -destination "platform=iOS Simulator,name=${{ inputs.device }},OS=${{ inputs.os }}" \
                   -testPlan "${{ inputs.testPlan }}" \
                   -enableCodeCoverage "${{ inputs.enableCodeCoverage }}" \
                   clean build test
      shell: bash