name: "Build Gradle for Android"
description: "Builds gradle excluding linting"

runs:
  using: "composite"
  steps:
    - name: Gradle Build
      run: |
        ./gradlew build -x lint
      shell: bash