name: "Android Build"

on:
  workflow_call:
    inputs:
      dummy:
        required: false
        type: string

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Build
        uses: mtdtechnology-net/github-actions/.github/actions/android-build-gradle@v55