name: dummy

on:
  workflow_call:
    inputs:
      env:
        required: false
        type: string
        default: dev
    #secrets:
    #  sa-key:
    #    required: false

jobs:
  dummy:
    name: dummy
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4